name: "GEOdnet Headless Console API"
description: "API for GEOdnet Console data"
version: "1.0.1"
slug: "geodnet_headless_console_api"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  3000/tcp: 3000
webui: "http://[HOST]:[PORT:3000]"
options:
  refresh_interval: 60
  inactivity_timeout: 5
schema:
  refresh_interval: int
  inactivity_timeout: int