name: "GEOdnet Headless Console API"
description: "API for GEOdnet Console data"
version: "1.0.2"
slug: "geodnet_headless_console_api"
init: false
arch:
  - amd64
ports:
  3000/tcp: 3000
options:
  server: "http://geodnet.local:3000"
  refresh_interval: 60
  inactivity_timeout: 5
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  refresh_interval: int
  inactivity_timeout: int
startup: application
url: "https://github.com/erikarenhill/geodnet-headless-console-api"